### PR TITLE
Adding requirements file

### PR DESCRIPTION
**Pull request by ChrisByrd14**

### CODE REVIEW

**Review by wowpin — COMMENTED** [review]
Could you briefly explain how does the requirements.txt work? Also what is the meaning of the extra lines in nohup? Afraid I'm not familiar with this.

Thanks!

**Comment by ChrisByrd14** [comment]
The requirements file allows people who clone the repo to install all the needed requirements with one simple command:

```bash
pip install -r requirements.txt
```

If you clone the repo to a fresh environment and run the above command, all the dependencies of this project will be installed. This allows users to run the application and without having to stop when it fails to import a library and manually install it (as I did).

The extra diff in `.gitignore` will go away when I make this next commit.

**Comment by wowpin** [comment]
Makes sense, thanks for that! I'll merge it along with the next version release.

Many thanks!

**Comment by wowpin** [comment]
Added.

**Pull request closed without merging**
